### ISSUE TITLE
项目启动失败。请问哪里出现问题？是不是需要配置钉钉之类的？

### ISSUE THREAD

**Issue by arraycto** [nju-softeng/dingtalk-app-back-end#46]

**Comment by arraycto** [comment]
![image](https://user-images.githubusercontent.com/37463247/139635453-573c5a5f-429a-4e07-b528-d3e5a740ba89.png)

**Comment by zhanyeye** [comment]
首先你这边要将后端代码也启动哇~
1. 去钉钉开发者后台创建自己的微应用
2. 获取 钉钉微应用相关配置信息， 例如：corpid, app_key, app_secret, agent_id,
    >  修改后端配置文件： [application-dev.properties](https://github.com/zhanyeye/dingtalk-springboot/blob/master/src/main/resources/application-dev.properties)
3. 启动后端会提提示 入口IP不在白名单的异常，拷贝异常中显示的ip地址，去钉钉开发者后台配置 ip 白名单。
基本ok

**Comment by zhanyeye** [comment]
截图中的情况是后端启动失败了，你看看控制台的保存信息~
