### ISSUE TITLE
Bug(controller.VoteController并发问题)

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-back-end#63]
createVote方法需要同步

**Comment by zhanyeye** [comment]
这样题issue，别人可能定位不到哇！需要定位代码行号，github 提供了这种功能
![image](https://user-images.githubusercontent.com/35565811/142832750-ca314322-86ac-47d0-93e7-f94c43618fbf.png)
鼠标左键行号，再点击`...`按钮，按shift 选中多行~，点击 copy permalink 复制链接，或者点击 Reference in new issue 

**效果如下：**
```
https://github.com/nju-softeng/dingtalk-app-back-end/blob/424fd68f95a6035a4ff710494ed26c6556c4c58d/src/main/java/com/softeng/dingtalk/service/VoteService.java#L77-L84
```
https://github.com/nju-softeng/dingtalk-app-back-end/blob/424fd68f95a6035a4ff710494ed26c6556c4c58d/src/main/java/com/softeng/dingtalk/service/VoteService.java#L77-L84

你也试试看
